### ISSUE TITLE
Enable the latest StrongSwan and VPP

### ISSUE THREAD

**Issue by mestery** [mestery/vpp-container-fun#20]
Some combination of VPP 18.10 and the latest StrongSwan code + VPP patch does not work, it causes the charon code to crash over and over. This needs investigating.

**Comment by mestery** [comment]
A backtrace of what is happening when charon dies:

```
[root@bc7a0d7385a7 ~]# gdb /usr/local/libexec/ipsec/charon ./vgcore.455 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/libexec/ipsec/charon...done.
[New LWP 455]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000006aed7fd in mspace_malloc () from /lib64/libvppinfra.so.18.10
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 vpp-lib-18.10-release.x86_64
(gdb) bt
#0  0x0000000006aed7fd in mspace_malloc () from /lib64/libvppinfra.so.18.10
#1  0x0000000006aef1b8 in mspace_get_aligned () from /lib64/libvppinfra.so.18.10
#2  0x0000000006ae4870 in vec_resize_allocate_memory () from /lib64/libvppinfra.so.18.10
#3  0x0000000006a9aafb in va_format () from /lib64/libvppinfra.so.18.10
#4  0x0000000006a99c57 in format () from /lib64/libvppinfra.so.18.10
#5  0x000000000684cd0e in svm_map_region () from /lib64/libsvm.so.18.10
#6  0x000000000684d5b4 in svm_region_init_internal () from /lib64/libsvm.so.18.10
#7  0x000000000684d7f0 in svm_region_init_chroot () from /lib64/libsvm.so.18.10
#8  0x0000000006631114 in vl_map_shmem () from /lib64/libvlibmemoryclient.so.18.10
#9  0x00000000066325fb in vl_client_api_map () from /lib64/libvlibmemoryclient.so.18.10
#10 0x00000000064296fa in vac_create (name=name@entry=0x64297fa "strongswan") at kernel_vpp_shared.c:569
#11 0x000000000642572a in kernel_vpp_plugin_create () at kernel_vpp_plugin.c:90
#12 0x0000000004e69d0d in create_plugin (handle=handle@entry=0x5f143b0, name=name@entry=0x5f14150 "kernel-vpp", integrity=integrity@entry=true, critical=critical@entry=false, 
    entry=entry@entry=0x1ffeffe970, this=0x5efe220) at plugins/plugin_loader.c:391
#13 0x0000000004e6a68b in load_plugin (this=0x5efe220, critical=false, file=<optimized out>, name=0x5f14150 "kernel-vpp") at plugins/plugin_loader.c:458
#14 load_plugins (this=0x5efe220, 
    list=0x402508 "aes des rc2 sha2 sha1 md5 mgf1 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem fips-prf gmp curve25519 xcbc cmac hmac attr kernel-netlink resolve socket-"...) at plugins/plugin_loader.c:1256
#15 0x00000000050b41b5 in initialize (this=<optimized out>, 
    plugins=0x402508 "aes des rc2 sha2 sha1 md5 mgf1 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem fips-prf gmp curve25519 xcbc cmac hmac attr kernel-netlink resolve socket-"...) at daemon.c:894
#16 0x000000000040180e in main (argc=1, argv=0x1fff0000a8) at charon.c:407
(gdb) 
```
